ADC disparado por TIM: Src/tim.c File Reference
tim.c File Reference
#include "tim.h"
Functions
void MX_TIM3_Init (void)
void MX_TIM10_Init (void)
void HAL_TIM_Base_MspInit (TIM_HandleTypeDef *tim_baseHandle)
void HAL_TIM_Base_MspDeInit (TIM_HandleTypeDef *tim_baseHandle)
Variables
TIM_HandleTypeDef htim3
TIM_HandleTypeDef htim10
Function Documentation
HAL_TIM_Base_MspDeInit()
void HAL_TIM_Base_MspDeInit (TIM_HandleTypeDef * tim_baseHandle)
Definition at line 126 of file tim.c.
HAL_TIM_Base_MspInit()
void HAL_TIM_Base_MspInit (TIM_HandleTypeDef * tim_baseHandle)
Definition at line 91 of file tim.c.
MX_TIM10_Init()
void MX_TIM10_Init (void)
Definition at line 76 of file tim.c.
References Error_Handler(), and htim10.
Referenced by main().
MX_TIM3_Init()
void MX_TIM3_Init (void)
Definition at line 46 of file tim.c.
References Error_Handler(), and htim3.
Referenced by main().
Variable Documentation
htim10
TIM_HandleTypeDef htim10
Definition at line 43 of file tim.c.
Referenced by MX_TIM10_Init(), and TIM1_UP_TIM10_IRQHandler().
htim3
TIM_HandleTypeDef htim3
File Name : TIM.c Description : This file provides code for the configuration of the TIM instances.
COPYRIGHT(c) 2017 STMicroelectronics
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of STMicroelectronics nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition at line 42 of file tim.c.
Referenced by MX_TIM3_Init(), and TIM3_IRQHandler().